// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw8b9rzGvuQ_JeYINRrIMekw4A4yKcVnw',
    appId: '1:55712418397:web:b7c155cecdcef863bb1bb4',
    messagingSenderId: '55712418397',
    projectId: 'careconnect-687c3',
    authDomain: 'careconnect-687c3.firebaseapp.com',
    storageBucket: 'careconnect-687c3.firebasestorage.app',
    measurementId: 'G-51FKNJQQD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdaEliFsQpK5cG2fRMlxq7fTKmHLmUyY0',
    appId: '1:55712418397:android:f278c7b473cdd496bb1bb4',
    messagingSenderId: '55712418397',
    projectId: 'careconnect-687c3',
    storageBucket: 'careconnect-687c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHGrJ5GAJbFV2b8i0_6bX97f-k1NL6l9w',
    appId: '1:55712418397:ios:05d81d6adbe754a1bb1bb4',
    messagingSenderId: '55712418397',
    projectId: 'careconnect-687c3',
    storageBucket: 'careconnect-687c3.firebasestorage.app',
    iosBundleId: 'com.careconnect.careconnectFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHGrJ5GAJbFV2b8i0_6bX97f-k1NL6l9w',
    appId: '1:55712418397:ios:05d81d6adbe754a1bb1bb4',
    messagingSenderId: '55712418397',
    projectId: 'careconnect-687c3',
    storageBucket: 'careconnect-687c3.firebasestorage.app',
    iosBundleId: 'com.careconnect.careconnectFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw8b9rzGvuQ_JeYINRrIMekw4A4yKcVnw',
    appId: '1:55712418397:web:78ab7c8a9c72b330bb1bb4',
    messagingSenderId: '55712418397',
    projectId: 'careconnect-687c3',
    authDomain: 'careconnect-687c3.firebaseapp.com',
    storageBucket: 'careconnect-687c3.firebasestorage.app',
    measurementId: 'G-6R5SSJ388X',
  );
}
